name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Generar archivo
        id: step_1
        run: |
          echo "archivo prueba, hola" >> test.log

        - name: Subir artefecto
          uses: actions/upload-artifact@v4
          with:
            name: archivo-test
            paths: test.log     